---
title: "DETECT Recruiting Dashboard"
# date: "Updated: `r Sys.Date()`"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
---

<!-- 
When refreshing, download the following to desktop:
  1. Participant scheduler
  2. Participant call log
  3. Phone recruitment
  4. Gift card
-->

<!-- 
Packages:
  1. rmarkdown
  2. dplyr
  3. DBI
  4. odbc
  5. Keyring
  6. purrr
  7. stringr
  8. hms
  9. lubridate
  10. forcats
  11. readr
  12. flexdashboard
  13. tidyr
  14. ggplot2
  15. plotly
  16. knitr
-->

```{r setup}
library(flexdashboard)
library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)

source("make_posixct.R") # Used to convert dates to POSIXct
```

```{r data}
# To make development faster, I'm downloading the data from FM pro instead of connecting directly to FM Pro through ODBC.
call_log              <- readr::read_csv("/Users/bradcannell/Desktop/Participant Call Log.csv")
participant_scheduler <- readr::read_csv("/Users/bradcannell/Desktop/Participant Scheduler.csv")
gift_card             <- readr::read_csv("/Users/bradcannell/Desktop/Gift Card.csv")
moca                  <- readr::read_csv("/Users/bradcannell/Desktop/Phone Recruitment.csv")
```


```{r}
# To make development faster, I'm moving all the data wrangling from data_import.R to this file.

# =============================================================================
# Initial data wrangling
#   - Convert all variable names to snake case
#   - Convert timestamps to POSIXct class (combine like commands across data frames later)
# =============================================================================
df_list <- list(call_log, participant_scheduler, gift_card, moca)
# Convert all variable names to snake case
df_list_2 <- purrr::map(
  # Grab the names of all data frames in the global envrironment
  .x = df_list,
  .f = function(x) {
    # Grab the variables names
    var_names <- names(x)
    # Convert variable names to snake case
    var_names <- stringr::str_replace_all(var_names, '(\\B)([A-Z])', '_\\2')
    # Convert variable names to lower case
    var_names <- tolower(var_names)
    # Fix medstar_id
    var_names[var_names == "medstar_i_d"] <- "medstar_id"
    # assign back to the dataframe
    names(x) <- var_names
    # Replace df with new names in global environment
    # assign(x, df)
    # Return df
    x
  }
)

call_log              <- df_list_2[[1]]
participant_scheduler <- df_list_2[[2]]
gift_card             <- df_list_2[[3]]
moca                  <- df_list_2[[4]]


# Clean call_log
# -----------------------------------------------------------------------------
call_log <- call_log %>% 
  mutate(
    # Change classes
    x_created_timestamp  = make_posixct(x_created_timestamp),
    x_modified_timestamp = make_posixct(x_modified_timestamp),
    call_date            = as.Date(call_date, "%m/%d/%Y"),
    # Separate date and time
    created_date = as.Date(x_created_timestamp),
    created_time = hms::as_hms(x_created_timestamp),
    # Create a call time hour variable
    call_hour = lubridate::hour(created_time),
    # Fix call_date typos
    # If call_date is earlier than created_date, then set call_date equal to 
    # the date in x_created_timestamp.
    call_date = if_else(call_date < created_date, created_date, call_date),
    # If call_date or call_time are missing, use the record created timestamp
    call_date = if_else(is.na(call_date), created_date, call_date),
    call_time = if_else(is.na(call_time), created_time, call_time),
    # Add call day variable
    day = weekdays(call_date),
    day = forcats::fct_relevel(day, "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),
    # Fill-in missing record month and year
    x_record_month = if_else(is.na(x_record_month), months(created_date), x_record_month),
    x_record_year  = if_else(is.na(x_record_year), lubridate::year(created_date), x_record_year)
  )

# Check call hours - because we sometimes have problems with this
call_hours_in_df <- sort(unique(call_log$call_hour))
call_hours_expected <- c(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18)
if (!setequal(call_hours_in_df, call_hours_expected)) {
  stop(
    "There are unexpected call times in the call_log data. The following", 
    "times were expected: ", paste(call_hours_expected, collapse = ", "), 
    ". However, the following times appear in the data: ", 
    paste(call_hours_in_df, collapse = ", "), "."
  )
}

# Create a factor version of the call hour variable
call_log <- call_log %>% 
  mutate(call_hour_f = factor(call_hour, labels = c(
    "08-08:59", "09-09:59", "10-10:59", "11-11:59", "12-12:59", "13-13:59", 
    "14-14:59", "15-15:59", "16-16:59", "17-17:59", "18-18:59"
  )))

# Clean participant_scheduler
# -----------------------------------------------------------------------------
## Keep scheduled rows only
scheduled_ids <- participant_scheduler %>% 
  filter(!is.na(appointment_date))

## Keep only the information needed for merging with call log
scheduled_ids <- scheduled_ids %>% 
  select(x_created_timestamp, medstar_id) %>% 
  mutate(
    scheduled = 1L,
    # Change classes
    x_created_timestamp  = make_posixct(x_created_timestamp),
    # Separate date and time
    scheduled_date = as.Date(x_created_timestamp),
    scheduled_time = hms::as_hms(x_created_timestamp),
    # Create a call time hour variable
    scheduled_hour = lubridate::hour(scheduled_time),
    scheduled_hour_f = factor(
      scheduled_hour, 
      levels = c(10, 11, 12, 13, 14, 15),
      labels = c("10-10:59", "11-11:59", "12-12:59", "13-13:59", "14-14:59", "15-15:59")
    )
  ) %>% 
  select(-x_created_timestamp)


# Clean gift_card
# -----------------------------------------------------------------------------
## All we need at this point is the number of gift cards given out, i.e. rows
## in this data
n_completed <- nrow(gift_card)


# Clean moca
# -----------------------------------------------------------------------------
## Deidentify data for local storage
moca_deid <- moca %>% 
  select(phone_eligible_consent:phone_more_info)
```

```{r}
# The notes column creates an error due to non-UTF-8 characters in the string. I could try to convert the strings to UTF-8, but I don't really need the notes at this point.
call_log <- call_log %>% select(-notes)
```



```{r}
# Make dataframe reactive
# Create date range selector
dateRangeInput('date_range',
  label = 'Select date range (inclusive): yyyy-mm-dd',
  start = min(call_log$call_date), end = Sys.Date()
)

# Use input to date range selector to filter dataframes
call_log_reactive <- reactive({
  call_log %>% 
    filter(call_date >= input$date_range[1] & call_date <= input$date_range[2])
})

renderTable({
  call_log_reactive()
})
```



